//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day_2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ITIExaminationSystemEntities : DbContext
    {
        public ITIExaminationSystemEntities()
            : base("name=ITIExaminationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<instructors> instructors { get; set; }
    
        public virtual int usp_addtrack(string trackName, string userName, string password)
        {
            var trackNameParameter = trackName != null ?
                new ObjectParameter("trackName", trackName) :
                new ObjectParameter("trackName", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_addtrack", trackNameParameter, userNameParameter, passwordParameter);
        }
    }
}
